### ISSUE TITLE
Performance on PascalVOC with DeepLabV3Plus(resnet50)

### ISSUE THREAD

**Issue by Beanocean** [yassouali/pytorch_segmentation#51]
I run the experiment on DeepLabV3Plus and use the same configuration as the PSPNet(resnet50) provided in the project. The mIoU only reach **_70.899_ after _80 epoch_** . After checking for several times, I still can't locate the error.  Do you have any advice? Besides, could you share the reproducible configuration of the DeepLabV3Plus?

**Comment by yassouali** [comment]
Hi, as mentioned in this issue https://github.com/yassouali/pytorch_segmentation/issues/29, I'll try to re-train the network and reproduce the trained model performance when I have a little of time (hopefully soon), but I suspect the performance drop might be due to the backbone I use that might have been updated. If you're up to it, try running with official resnet backbone used in pytorch segmentation or check the backbones in [torchcv](https://github.com/donnyyou/torchcv).

Please refer to the open issue for updates.
