### ISSUE TITLE
tesorboard

### ISSUE THREAD

**Issue by lkyw5210** [yassouali/pytorch_segmentation#62]
Hello, when I used tensorboard to visualize the log file, I found that the step on the training set was not consistent with the step on the verification set. For example, the training set had 35k steps but only 1.3k steps on the verification set. May I ask why

**Comment by yassouali** [comment]
It's simply due to the number of validation and training examples, since the step is computed as `epoch * len(dataloader)`, the number of validation step will be lower. We also only apply validation once every 5 of so epochs, but the training logs are done multiple times each training epoch.

Hope this helps
