### ISSUE TITLE
how to convert target images to segmentation maps

### ISSUE THREAD

**Issue by Gauravi24** [yassouali/pytorch_segmentation#68]

**Comment by Gauravi24** [comment]
i get an assert error .My targets are images and not segmentation maps.how do convert them to segmentation maps.I am using a custom dataset

**Comment by jegesh** [comment]
I'm also getting the assert error with a custom dataset, even though I converted my labels to the exact same format as the VOC dataset

**Comment by jegesh** [comment]
(this issue)[https://github.com/yassouali/pytorch_segmentation/issues/2] helped me figure out what to fix

**Comment by Gauravi24** [comment]
thank you
could you help me use argmax?

**Comment by Gauravi24** [comment]
Also my targets are of the shape BHWC where C is channel for me not number of classes

**Comment by Gauravi24** [comment]
i am confused of the target mask what format should it be and how should i
do it.I am new to pytorch and segmentation

**Comment by jegesh** [comment]
You first need to choose a data format and build a DataSet class that subclasses `BaseDataSet`, for instancing I was already using pascal-VOC so I copied the `VOCDataset` class and modified it to my needs (also I needed to change the last few lines of the `VOC` class constructor so that it used my dataset class).
As far as the mask, I fed it a numpy array of shape `(height, width)`, taking the dimensions from the label image, and the actual values were the channel indexes for each value.  I already a 28-channel one-hot mask (for 27 classes and background), so then I just used these two lines to convert it:
```
label = np.argmax(label_arr,2)
label = np.asarray(label, dtype=np.int32)
```

**Comment by jegesh** [comment]
Shortly after I got it to work, I realized I actually need Object Notation for my project and not segmentation, so I can't help you any further, but you may need to swap the axes in the label ndarray, because of the different conventions between numpy and image libraries (in numpy y,x is the convention, and many other libraries use x,y for axis order)

**Comment by yassouali** [comment]
thank you @jegesh for helping out.
